-- Create users table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create companies table (with address field)
CREATE TABLE companies (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    address VARCHAR2(500),
    owner_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_company_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

-- Create user_companies table
CREATE TABLE user_companies (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    company_id NUMBER NOT NULL,
    role VARCHAR2(10) CHECK (role IN ('OWNER', 'MEMBER')) NOT NULL,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_company_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_company_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT uk_user_company UNIQUE (user_id, company_id)
);

-- Create expenses table
CREATE TABLE expenses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    amount NUMBER(10,2) NOT NULL,
    description VARCHAR2(255),
    category VARCHAR2(50),
    expense_date DATE,
    status VARCHAR2(10) CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP,
    approved_by NUMBER,
    CONSTRAINT fk_expense_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_expense_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_expense_approver FOREIGN KEY (approved_by) REFERENCES users(id)
);